{% set version = "0.56.0" %}

package:
  name: containers-common
  version: {{ version }}

source:
  - url: https://github.com/containers/common/archive/v{{ version }}.tar.gz
    sha256: a981ff8746cf193fda0caccb9cd0deac121e334dfa0de6f441ad7ebb267f1109
    folder: common
  # NOTE: Due to historic reasons, some configs are from the skopeo project.
  #       When updating, please
  #        1. check if those were added to containers-common in the meantime,
  #        2. be sure to update to a newer skopeo source if there are new changes!
  - url: https://github.com/containers/skopeo/archive/v1.13.3.tar.gz
    sha256: 0b788fc5725ac79327f7c29797821a2bafc1c3c87bbfcb2998c2a1be949e314d
    folder: skopeo
  # NOTE: When updating to a newer buildah source archive,
  #        1. check if registries.conf has already been added to containers-common,
  #        2. make sure that tests/registries.conf is a plain and simple as of version 1.17.0.
  - url: https://github.com/containers/buildah/archive/v1.32.0.tar.gz
    sha256: 806ed541ea3cc761e0fa2dde8c6ee2d6ed258baf1cc5bd72b6b0cf1e876dda15
    folder: buildah

build:
  number: 0
  skip: true  # [win]

test:
  commands:
    # Package does not include empty directory due to conda-build issue:
    #   https://github.com/conda/conda-build/issues/1014
    # - test -d "${PREFIX}/etc/containers/registries.conf.d"
    - grep -qF quay.io "${PREFIX}/etc/containers/registries.conf"
    - grep -qF docker.io "${PREFIX}/etc/containers/registries.conf"
    - |
      grep -qF 'sigstore-staging: file:///var/lib/containers/sigstore' "${PREFIX}/etc/containers/registries.d/default.yaml"
    - grep -qF docker-daemon "${PREFIX}/etc/containers/policy.json"
    - |
      grep -qF '"defaultAction": "SCMP_ACT_ERRNO",' "${PREFIX}/share/containers/seccomp.json"  # [linux]
    - |
      test 4 -eq "$( grep -cF "${PREFIX}" "${PREFIX}/share/containers/containers.conf" )"  # [linux]

about:
  home: https://github.com/containers/common
  dev_url: https://github.com/containers/common
  doc_url: https://github.com/containers/common
  license: Apache-2.0
  license_file: common/LICENSE
  summary: Location for shared common files in github.com/containers repos.

extra:
  recipe-maintainers:
    - mbargull
    - ngam
    - AndreasAlbertQC
