build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
test_on_native_only: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
github:
  branch_name: main
  tooling_branch_name: main
bot:
  version_updates:
    exclude:
      - '1.31.1'
      - '1.0.1'
conda_build:
  pkg_format: '2'
azure:
  store_build_artifacts: True
